function d2E_dT2 = d2E_dT2_4cov(in1,in2,in3,in4)
%D2E_DT2_4COV
%    D2E_DT2 = D2E_DT2_4COV(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    27-Jun-2012 13:14:09

d2E_dT2 = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0],[3, 3]);
