function dE_dT = dE_dT_4cov(in1,in2,in3,in4)
%DE_DT_4COV
%    DE_DT = DE_DT_4COV(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    27-Jun-2012 13:14:06

T1 = in4(1,:);
T2 = in4(2,:);
T3 = in4(3,:);
f_n1 = in2(1,:);
f_n2 = in2(2,:);
f_n3 = in2(3,:);
f_p1 = in1(1,:);
f_p2 = in1(2,:);
f_p3 = in1(3,:);
q1 = in3(1,:);
q2 = in3(2,:);
q3 = in3(3,:);
q4 = in3(4,:);
t2 = q1.^2;
t3 = q2.^2;
t4 = q3.^2;
t5 = q4.^2;
t6 = q1.*q4.*2.0;
t7 = q1.*q3.*2.0;
t8 = q2.*q4.*2.0;
t9 = q1.*q2.*2.0;
dE_dT = [T1-f_p1+f_n3.*(t7+t8)+f_n1.*(t2+t3-t4-t5)-f_n2.*(t6-q2.*q3.*2.0);T2-f_p2+f_n2.*(t2-t3+t4-t5)+f_n1.*(t6+q2.*q3.*2.0)-f_n3.*(t9-q3.*q4.*2.0);T3-f_p3-f_n1.*(t7-t8)+f_n3.*(t2-t3-t4+t5)+f_n2.*(t9+q3.*q4.*2.0)];
