function dv_dQ = dv_dq_(in1)
%DV_DQ
%    DV_DQ = DV_DQ(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    28-Jun-2012 06:47:05

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = q2.^2;
t3 = q3.^2;
t4 = q4.^2;
t5 = t2+t3+t4;
t6 = 1.0./sqrt(t5);
t7 = acos(q1);
t8 = 1.0./t5.^(3.0./2.0);
t9 = q1.^2;
t10 = -t9+1.0;
t11 = 1.0./sqrt(t10);
t12 = t6.*t7.*2.0;
dv_dQ = reshape([q2.*t6.*t11.*-2.0,q3.*t6.*t11.*-2.0,q4.*t6.*t11.*-2.0,t12-t2.*t7.*t8.*2.0,q2.*q3.*t7.*t8.*-2.0,q2.*q4.*t7.*t8.*-2.0,q2.*q3.*t7.*t8.*-2.0,t12-t3.*t7.*t8.*2.0,q3.*q4.*t7.*t8.*-2.0,q2.*q4.*t7.*t8.*-2.0,q3.*q4.*t7.*t8.*-2.0,t12-t4.*t7.*t8.*2.0],[3, 4]);
