function H = observe_heading_jac(in1)
%OBSERVE_HEADING_JAC
%    H = OBSERVE_HEADING_JAC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    27-Jun-2012 13:38:38

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = q2.*2.0;
t3 = q3.*2.0;
t4 = q1.*2.0;
H = reshape([q4.*-2.0,t4,t2,t3,-t2,t4,t2,t3,q4.*2.0,q1.*-2.0,q4.*-2.0,t3],[3, 4]);
